# Generated by Django 4.2.1 on 2023-06-20 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_title_phone_version_phone_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('resolution', models.CharField(max_length=20)),
                ('os', models.CharField(max_length=20)),
                ('memory', models.IntegerField()),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.phone')),
            ],
        ),
    ]
