# Generated by Django 4.2.1 on 2023-06-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_chars'),
    ]

    operations = [
        migrations.AddField(
            model_name='chars',
            name='order_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chars',
            name='views_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
