# Generated by Django 4.2.2 on 2023-06-24 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0007_remove_basket_phone_remove_order_expire_date_and_more'),
        ('shop', '0004_chars_order_count_chars_views_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brawl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('price', models.IntegerField()),
                ('available', models.BooleanField()),
                ('views_count', models.IntegerField()),
                ('order_count', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='phone',
            name='company',
        ),
        migrations.RenameModel(
            old_name='Company',
            new_name='Character',
        ),
        migrations.DeleteModel(
            name='Chars',
        ),
        migrations.DeleteModel(
            name='Phone',
        ),
        migrations.AddField(
            model_name='brawl',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.character'),
        ),
    ]
