# Generated by Django 4.2.2 on 2023-06-24 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_brawl_remove_phone_company_rename_company_character_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brawl',
            name='image',
            field=models.ImageField(default=0, upload_to='django_lab/shop/static/'),
            preserve_default=False,
        ),
    ]
