# Generated by Django 4.2.1 on 2023-06-21 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0003_alter_order_cvc'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='datetime',
            field=models.DateField(default='2023-06-21'),
        ),
    ]
