# Generated by Django 4.2.1 on 2023-06-21 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0004_basket_price_alter_order_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='price',
        ),
    ]
