# Generated by Django 4.2.1 on 2023-06-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0005_remove_basket_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='all_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
