# Generated by Django 4.2.2 on 2023-06-24 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0006_order_all_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='expire_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='last_name',
        ),
    ]
