# Generated by Django 4.2.2 on 2023-06-24 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0007_remove_basket_phone_remove_order_expire_date_and_more'),
        ('shop', '0005_brawl_remove_phone_company_rename_company_character_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='brawl',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='shop.brawl'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='datetime',
            field=models.DateField(default='2023-06-24'),
        ),
    ]
